---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-tools
  labels:
    name: dev-tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-tools
  namespace: dev-tools
  labels:
    app: dev-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-tools
  template:
    metadata:
      labels:
        app: dev-tools
    spec:
      containers:
      - name: dev-tools
        image: registry.suse.com/bci/bci-busybox:15.5
        imagePullPolicy: IfNotPresent
        command: [ "sleep", "3600" ]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: EXAMPLE_ENV_VAR
          value: "Hello, Dev Tools!"
        # Optional: Define ports if needed
        # ports:
        # - containerPort: 80
---
# Optional: Service Definition (Uncomment if you need to expose the Deployment)
# apiVersion: v1
# kind: Service
# metadata:
#   name: dev-tools-service
#   namespace: dev-tools
#   labels:
#     app: dev-tools
# spec:
#   selector:
#     app: dev-tools
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: ClusterIP