apiVersion: v1
kind: Pod
metadata:
  name: parts-lib-mini-db
  labels:
    app: parts-lib-mini-db
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
