# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: palace-arcade-lb
spec:
  selector:
    app: palace-arcade
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
