apiVersion: v1
kind: Pod
metadata:
  name: mini-db
  labels:
    app: mini-db
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3500"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
